# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100, verbose_name='incident type descriptor(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateTimeField()),
                ('i_date', models.DateField(verbose_name='incident date')),
                ('i_time', models.TimeField(verbose_name='incident time')),
                ('i_type', models.CharField(max_length=3, verbose_name='incident type')),
                ('text_description', models.TextField(verbose_name='incident description')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bias_tracker.Author')),
                ('i_descriptors', models.ManyToManyField(to='bias_tracker.Descriptor', verbose_name='incident type descriptor(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='i_subject_id',
            field=models.ManyToManyField(to='bias_tracker.Subject', verbose_name='incident subject(s)'),
        ),
    ]
