# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bias_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Person',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='i_subject_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='incident_as_subjects', to='bias_tracker.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='subjects',
            field=models.ManyToManyField(related_name='incidents_as_author', to='bias_tracker.Person'),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='descriptor',
            field=models.CharField(max_length=100, verbose_name='Incident Type Descriptor(s)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='filing_date',
            field=models.DateTimeField(verbose_name='Filing Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='i_date',
            field=models.DateField(verbose_name='Incident Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='i_descriptors',
            field=models.ManyToManyField(to='bias_tracker.Descriptor', verbose_name='Descriptors of Incident Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='i_time',
            field=models.TimeField(blank=True, verbose_name='Incident Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='i_type',
            field=models.CharField(choices=[('Exclusion', 'Exclusion'), ('Inclusion', 'Inclusion')], max_length=10, verbose_name='Incident Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='text_description',
            field=models.TextField(verbose_name='Incident Description'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
