# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 5, 0, 25, 33, 644885)),
        ),
    ]
