# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bias_tracker', '0002_auto_20160526_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='descriptors',
            field=models.ManyToManyField(to='bias_tracker.Descriptor'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subjects',
            field=models.ManyToManyField(to='bias_tracker.Person'),
        ),
    ]
