# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_tracker', '0003_auto_20160605_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default='2016-01-01'),
        ),
    ]
